include: package:effective_dart/analysis_options.1.2.0.yaml

linter:
  rules:
    public_member_api_docs: false
    constant_identifier_names: false
    use_setters_to_change_properties: false
    omit_local_variable_types : false