name: Hemoliga
description: 'Conectando vidas através da doação de sangue.'

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  liquid_swipe: ^1.4.3
  flare_flutter: ^2.0.3
  circular_check_box: ^1.0.1
  datetime_picker_formfield: ^1.0.0
  splashscreen: ^1.2.0
  # Service locator
  get_it: ^4.0.1
  # Local cache
  #shared_preferences: ^0.5.6+3
  # Remote API
  data_connection_checker: ^0.3.4
  dio: ^3.0.9
  # Funtional programming thingies    
  dartz: ^0.8.9
  # Value equality
  equatable: ^1.1.1
  # Store controller
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  # Modular estructure
  flutter_modular: ^1.0.0
  flutter:
    sdk: flutter    
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  effective_dart: ^1.2.1
  mockito: ^4.1.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/animations/
     - lib/app/core/lang/pt.json
     - lib/app/core/lang/en.json

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: IconsHemoliga
      fonts:
        - asset: assets/fonts/IconsHemoliga.ttf        

scripts: 
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs  